server:
  port: 8083

spring:
  application:
    name: EMPLOYEE-SERVICE

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/